### PR TITLE
CHK-720: parameter `refreshOutdatedData` in `orderForm` query

### PR DESCRIPTION
**Pull request by silviasfon**
#### What problem is this solving?

Adding the parameter that will allow the orderForm to be updated when needed 

#### How should this be manually tested?

[Here](https://contextualpipeline--checkoutio.myvtex.com/_v/private/vtex.checkout-graphql@0.58.0/graphiql/v1?query=mutation%7B%0A%20%20updateItems(orderItems%3A%20%7B%0A%20%20%20%20index%3A%200%0A%20%20%20%20quantity%3A%202%0A%20%20%7D%2C%20allowedOutdatedData%3A%20%5B%22paymentData%22%5D)%7B%0A%09%09items%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20quantity%0A%20%20%20%20%7D%0A%20%20%20%20value%0A%20%20%20%20paymentData%7B%0A%20%20%20%20%20%20installmentOptions%7B%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D), change the quantity field and run the mutation. Then, run [this](https://contextualpipeline--checkoutio.myvtex.com/_v/private/vtex.checkout-graphql@0.58.0/graphiql/v1?query=query%7B%0A%20%20orderForm(orderFormId%3A%20%22962138e7c89b45bc80246d9ef750e97a%22%2C%0A%20%20refreshOutdatedData%3A%20false)%7B%0A%20%20%20%20value%0A%20%20%20%20items%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20quantity%0A%20%20%20%20%7D%0A%20%20%20%20paymentData%7B%0A%20%20%20%20%20%20installmentOptions%7B%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) query and check that the `value` field in orderForm differs from the fields `value` in `installmentOptions`. Change `refreshOutdatedData` value to true and run the query. Check if the those values are now equal.

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [x] Linked this PR to a Jira story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking change 
_ | Technical improvements

### CODE REVIEW

**Review by wdsrocha — APPROVED** [review]

**Review by lucasecdb — COMMENTED** [review]
LGTM, but can we not format the changelog? :-(

**Comment by wdsrocha** [comment]
> LGTM, but can we not format the changelog? :-(

@lucasecdb we formatted it by mistake, so I unformatted it and realized that there wasn't a pattern - some old changelogs were with spaces. So I reformatted it :S

That being said, do you still think it's better to keep everything untouched?

**Comment by lucasecdb** [comment]
> That being said, do you still think it's better to keep everything untouched?

I'd prefer leaving it untouched. The main reason is that on the old "format" we have fewer git conflicts when someone merges/deploys a PR before yours, so it's just one less rebase to do :P

**Comment by wdsrocha** [comment]
> I'd prefer leaving it untouched. The main reason is that on the old "format" we have fewer git conflicts when someone merges/deploys a PR before yours, so it's just one rebase less to do :P

done!

**Review by lucasecdb — APPROVED** [review]

**Review by wdsrocha — APPROVED** [review]

**Pull request merged**
